[versions]
armeria = "1.41.1"
jackson = "2.22.3"
slf4j = "2.0.18"
logback = "1.6.4"
junit = "6.1.3"
onnxruntime = "1.29.0"
djl = "0.36.0"
hdrhistogram = "2.2.2"
langchain4j = "1.20.1"
langchain4j-beta = "1.20.1-beta30"

[libraries]
armeria-bom = { module = "com.linecorp.armeria:armeria-bom", version.ref = "armeria" }
armeria = { module = "com.linecorp.armeria:armeria" }
armeria-junit5 = { module = "com.linecorp.armeria:armeria-junit5" }
armeria-prometheus1 = { module = "com.linecorp.armeria:armeria-prometheus1" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml" }
onnxruntime = { module = "com.microsoft.onnxruntime:onnxruntime", version.ref = "onnxruntime" }
onnxruntime-gpu = { module = "com.microsoft.onnxruntime:onnxruntime_gpu", version.ref = "onnxruntime" }
djl-tokenizers = { module = "ai.djl.huggingface:tokenizers", version.ref = "djl" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
hdrhistogram = { module = "org.hdrhistogram:HdrHistogram", version.ref = "hdrhistogram" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
langchain4j-cohere = { module = "dev.langchain4j:langchain4j-cohere", version.ref = "langchain4j-beta" }
langchain4j-open-ai-official = { module = "dev.langchain4j:langchain4j-open-ai-official", version.ref = "langchain4j-beta" }
langchain4j-http-client-jdk = { module = "dev.langchain4j:langchain4j-http-client-jdk", version.ref = "langchain4j" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
